### ISSUE TITLE
Stat is not reporting

### ISSUE THREAD

**Issue by Sunnygtiff** [samueljun/tomato-clock#82] opened 2020-06-23 22:11 UTC
**Describe the bug**
It's not counting what I did at all today!

**To Reproduce**
It did not track any breaks nor tomatoes.

**Expected behavior**
It should track it

**Desktop (please complete the following information):**

- OS: Window 10
- Browser Chrome
- Version  5.0.3

**Comment by Agent49** [comment] 2020-07-30 12:53
Same here. In my case records not working for firefox anymore (yesterday they did). In chrome however, records are working.

**Desktop (please complete the following information):**

- OS: Window 10
- Browser Firefox
- Version 79.0 (64bit)

**Comment by Sunnygtiff** [comment] 2020-07-30 13:52
It was working in Chrome for a couple of weeks then it stopped working.

**Comment by Agent49** [comment] 2020-07-30 16:09
In my case it stopped working today when using firefox. I just installed it in chrome where it worked fine. But Firefox is my default Browser.

**Comment by AlyssonR** [comment] 2020-07-30 20:22
Same here. Stopped working today. (Firefox 79.0 in Ubuntu).

**Comment by samueljun** [comment] 2020-08-02 15:22
Hey folks, thanks for the bug reports. Could someone do the following to help me debug the issue?

1. Complete a Tomato
1. Go to Stats
1. Confirm that the Tomato didn't tracked
1. "Export Stats as JSON" and attach it here?

The stats file will help me at least confirm if the issue is the underlying data tracking or with a rendering bug on the Stats page.

**Comment by Sunnygtiff** [comment] 2020-08-03 00:18
Window 10
Chrome
Tomato Clock 5.2.0

**Comment by Agent49** [comment] 2020-08-03 10:11
I can confirm, it did not record the tomato I just finished. It's not a rendering bug, it's not written to the json-file. See attachement.

[tomato-clock-stats.zip](https://github.com/samueljun/tomato-clock/files/5015297/tomato-clock-stats.zip)

**Comment by mishasan** [comment] 2020-08-03 12:35
Hey, same here

Windows 10
Firefox (79.0 64Bit)
Tomato Clock 5.2.0

See my JSON Export from just now (2020_08-03) after tracking 2 tomatoes and 2 short breaks:
[{"date":"2019-06-13T13:00:08.000Z","timeout":1500000,"type":"tomato"},

.... MORE DATA ...

{"date":"2019-12-17T09:11:57.000Z","timeout":1500000,"type":"tomato"},{"date":"2019-12-17T14:22:30.000Z","timeout":300000,"type":"shortBreak"},{"date":"2019-12-17T14:53:34.000Z","timeout":1500000,"type":"tomato"},{"date":"2020-01-31T13:27:48.000Z","timeout":300000,"type":"shortBreak"}]

To me, it seems that it does not track data anymore (have not been using it a while, so I can't tell when it stopped).
The diagram view is okay: If I change the range to the last year it displays the graph from December 2019 as in my JSON from above. Hope that helps.
Greetings.

**Comment by whym** [comment] 2020-08-03 15:26
I experienced the same issue with Firefox 79.0 on Ubuntu. I tried a couple of things (after exporting the data) :

- I was able to start from scratch. Resetting the stats worked - after all the data were removed, sessions started to get counted.
- Another thing I tried was to remove old entries from the exported file, have it under 6 kb, and import it. This also worked.
- I couldn't import the original 60+ kb JSON file I exported - when I tried, no data showed up. There was this line in the console log: `Uncaught (in promise) Error: QuotaExceededError: storage.sync API call exceeded its quota limitations`. It pointed to `moz-extension://a59b936b-7bb3-4c59-b26a-fb1305ddd49a/stats/stats.js:298` .

At least for Firefox, the last point might be related to: https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/ (well, I'm not really sure, but the timing looks suspicious.)

**Comment by Agent49** [comment] 2020-08-04 11:54
@whym Resetting the stats helped me too. Thank you! And thanks to the author of this plugin, which helps me a lot to stay focussed in the home office these days . :)

**Comment by samueljun** [comment] 2020-08-08 04:12
Thanks for the link and console.log @whym! Also based on all the reports here, it sounds a lot like the issue is with the storage size limits.

I originally set the stats data to be stored on `storage.sync` so that the stats could be synced across all devices. However the size limits there are clearly too small for typical usage. Since the sync storage is clearly too small, I'm going to switch to `storage.local` as a first step. The limit there is much larger at 5 MB (~500x bigger). The caveat here is that the stats will only be stored on the local browser and won't be synced across all of your browsers anymore.

I'm not sure if folks found a lot of value in the stats being synced. If you did, I would say to follow up with a feature request for an option to use sync storage. And I could look at putting in an option allowing you to pick which storage you want, with disclaimers on the file size limits.

**Comment by samueljun** [comment] 2020-08-11 03:10
6.0.0 has been released with the fix, feel free to reopen if you're still seeing the issue!

**Closed** 2020-08-11 03:10 UTC
Labels: bug

**Comment by whym** [comment] 2020-09-02 07:52
I just wanted to note that (expectedly) the issue didn't reappear after the update so far. Thank you for the great work!
