### ISSUE TITLE
Add a feature to blacklist distracting websites

### ISSUE THREAD

**Issue by CookiePigeon** [samueljun/tomato-clock#68] opened 2019-04-01 09:21 UTC
Could you please add a feature that when the Pomodoro timer is active, a list of websites is restricted to access. The user could add URLs to the list if they want.
Also, when the break occurs all the blacklisted websites would become whitelisted and are able to be accessed during the break.

Thanks so much and this extension has worked amazingly!!

**Comment by samueljun** [comment] 2019-09-12 07:09
Closing as a duplicate of #56

**Closed by samueljun** 2019-09-12 07:09 UTC
Labels: enhancement
